toolbar:
  - styleselect | bold italic | forecolor backcolor | undo redo | image | link | table | codesample | code
plugins:
  - image
  - link
  - code
  - codesample
  - textcolor
  - table
  - autoresize
